Tildes arreglados
luisantonc/hyperblog pull request #1
Opened 2024-02-09 19:54 UTC by luisantonc

No se debe pasar este a main directamente, lo pase al header

2024-02-09 20:07 UTC, sofiantont commented on blogpost.html
En vez de usar tildes directas usa entidades html.

2024-02-09 20:09 UTC, sofiantont requested changes
En vez de usar tildes directas usa entidades HTML.

2024-02-09 20:22 UTC, luisantonc commented
cambios hechos por favor hazme el merge

2024-02-10 20:47 UTC, sofiantont approved these changes
Excelente. Eso era!!!.

2024-02-10 20:49 UTC, merged